Feature update comment
benedekhalaj/terraforming-mars-forum-api pull request #221
Opened 2022-09-21 11:33 UTC by Sagi-Viktor

- resolve #181

2022-09-21 13:00 UTC, Zsezsu approved these changes
nice job Viktor! :+1:

2022-09-22 09:33 UTC, benedekhalaj requested changes

2022-09-22 09:33 UTC, benedekhalaj commented on springboot/src/test/java/com/codecool/terraformingmarsforum/service/CommentServiceTest.java
> +    }
is this method used considering you implemented Mapstruct solution?

2022-09-22 09:33 UTC, benedekhalaj commented on springboot/src/test/java/com/codecool/terraformingmarsforum/service/CommentServiceTest.java
> +                .build();
I am not sure why you need to build these manually

2022-09-22 09:45 UTC, Sagi-Viktor commented on springboot/src/test/java/com/codecool/terraformingmarsforum/service/CommentServiceTest.java
> +    }
Yeah I need build a DTO to convert it

2022-09-22 09:45 UTC, Sagi-Viktor commented on springboot/src/test/java/com/codecool/terraformingmarsforum/service/CommentServiceTest.java
> +                .build();
Same as previus answer

2022-09-22 09:46 UTC, benedekhalaj approved these changes

2022-09-22 09:46 UTC, merged